config/routes.rb
SnapLeads::Application.routes.draw do
  resources :leads do
    resources :comments
  end
  devise_for :users
  root :to => 'leads#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :commentable, polymorphic: true

  default_scope order: 'comments.created_at DESC'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :company_name, :contact, :email, :notes, :phone, :website, :address, :city, :state, :zipcode, :company_type, :inactive, :latitude, :longitude
  def full_address
    [address, city, state, zipcode].compact.join(', ')
  end
  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  belongs_to :user
  has_many :comments, as: :commentable
  validates :company_name, presence: true, length: { maximum: 60 }
  validates :user_id, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  has_many :leads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_commentable

  def index
  	@commentable = Lead.find(params[:lead_id])
  	@comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment]) 
    if @comment.save
      redirect_to @commentable 
    else
    render :new 
    end
  end

private
  def load_commentable
  resource, id = request.path.split('/')[1,2]
  @commentable = resource.singularize.classify.constantize.find(id)
  end 
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :authenticate_user!
  # GET /leads
  # GET /leads.json
  def index
    @leads = current_user ? current_user.leads.all : nil

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])
    @commentable = @lead
    @comments = @commentable.comments 
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = current_user.leads.build(params[:lead])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comments.html.erb
<div id="comments">
<% @comments.each do |comment| %>
	<hr>
<div class="comment">
<%= simple_format comment.content %>
<div class="pull-right">
<small>
	<i><font color="grey">
	
	Added <%= time_ago_in_words(comment.created_at) %> ago
	</font></i>
</small>
</div>
</div> 
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %> <% if @comment.errors.any? %>
<div class="error_messages">
<h2>Please correct the following errors.</h2> <ul>
<% @comment.errors.full_messages.each do |msg| %>
<li><%= msg %></li> <% end %>
</ul>
</div> <% end %>
<div class="field">
<%= f.text_area :content, rows: 3, class: 'span6' %>
</div>
<div class="actions">
<%= f.submit class: 'btn btn-small btn-custom2' %> </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<%= render 'comments' %>
<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<hr>
	<small>
		© SnapLeads 2013
	</small>
</div>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
   
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- Be sure to leave the brand out there if you want it shown -->
        <%= link_to "SnapLeads", root_path, class: "brand" %>
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <% if user_signed_in? %>
            <li>
              <form class="navbar-form pull-right">
                <%= link_to "Add New Lead", new_lead_path, class: "btn btn-custom" -%>
              </form>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b>
              </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
                <ul>
            <% else %>

            <% end %>
          </ul>
          <!-- .nav, .navbar-search, .navbar-form, etc -->
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SnapLeads</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>	
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h4>

      <ul>
      <% @lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="span4">
  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_type %>
    <%= f.text_field :company_type %>
  </div>
    <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :contact %>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
    <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
</div>
<div class="span4">
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>
  <hr>
  <div class="field">
    <%= f.label :notes, 'Status' %>
    <%= f.text_area :notes, :rows => 2 %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
  </div>
  </div>
</div>
<% end %>

app/views/leads/edit.html.erb
<h3>Edit <%= @lead.company_name %></h3>
<hr>

<%= render 'form' %>

<%= link_to 'Cancel', leads_path, class: "btn btn-small" %>

app/views/leads/index.html.erb
<% if user_signed_in? %>
<div>
<table id="leads" class="display table-bordered table-hover">
    <thead>
      <tr>
        <th>Company</th>
        <th class="hidden-tablet hidden-phone hidden-desktop-small">Type</th>
        <th>Contact</th>
<!--         <th class="hidden-tablet hidden-phone hidden-desktop-small">Phone</th>
        <th class="hidden-tablet hidden-phone hidden-desktop-small">Email</th> -->
        <th class="hidden-tablet hidden-phone hidden-desktop-small">Status</th>
        <th class="hidden-tablet hidden-phone hidden-desktop-small">Updated</th>    
      </tr>
    </thead>
    <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= link_to lead.company_name, lead %></td>
        <td class="hidden-tablet hidden-phone hidden-desktop-small"><%= lead.company_type %></td>
        <td><%= lead.contact %></td>
<!--         <td class="hidden-tablet hidden-phone hidden-desktop-small"><%= lead.phone %></td>
        <td class="hidden-tablet hidden-phone hidden-desktop-small"><%= lead.email %></td> -->
        <td class="hidden-tablet hidden-phone hidden-desktop-small"><%= lead.notes %></td>
        <td class="hidden-tablet hidden-phone hidden-desktop-small"><%= lead.updated_at.strftime("%d %b %y %H:%M") %></td>    
      </tr>
    <% end %>
    </tbody>
</table>
</div>

<% else %>
<div class="hero-unit">
    <h1>SnapLeads</h1>
    <p>
        Dead simple CRM. You can comment, filter, and sort. That's it.
    </p>
        <br>
    <p>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-large" %>
        or
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-info btn-large" %>
    </p>
</div>

<% end %>

app/views/leads/new.html.erb
<h3>New lead</h3>
<hr>
<%= render 'form' %>

app/views/leads/show.html.erb
  <div class="container">
    <h3><%= @lead.company_name %></h3>
  </div>

  <div class="row well well-small">
    <div class="span5">
      <table class="table table-striped table-bordered table-hover">
        <tr>
          <td>
            Company Type:
          </td>
          <td>
            <%= best_in_place @lead, :company_type %>
          </td>
        </tr>
        <tr>
          <td>
            Contact:
          </td>
          <td>
            <%= best_in_place @lead, :contact %>
          </td>
        </tr>
        <tr>
          <td>
            Phone:
          </td>
          <td>
            <%= best_in_place @lead, :phone %>
          </td>
        </tr>
        <tr>
          <td>
            Email:
          </td>
          <td>
            <%= best_in_place @lead, :email %>
          </td>
        </tr>
          <tr>
          <td>
            Website:
          </td>
          <td>
            <%= @lead.website %>
          </td>
        </tr>
        <tr>
          <td>
            Address:
          </td>
          <td>
            <%= best_in_place @lead, :address %>
          </td>
        </tr>
        <tr>
          <td>
            City:
          </td>
          <td>
            <%= best_in_place @lead, :city %>
          </td>
        </tr>
        <tr>
          <td>
            State:
          </td>
          <td>
            <%= best_in_place @lead, :state %>
          </td>
        </tr>
        <tr>
          <td>
            Zip:
          </td>
          <td>
            <%= best_in_place @lead, :zipcode %>
          </td>
        </tr>
      </table>
      <%= link_to "<i class=\"icon-arrow-left\"></i>".html_safe, leads_path, class: "btn btn-small" -%>
      <%= link_to "<i class=\"icon-edit\"></i>".html_safe, edit_lead_path(@lead), class: "btn btn-small"  -%>
      <%= link_to "<i class=\"icon-trash\"></i>".html_safe, @lead, method: :delete, data: { confirm: 'Are you sure you want to delete this lead?' }, class: "btn btn-small" -%>
      <hr>
      <h4>Map:</h4>
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=600x150&sensor=false&zoom=12&markers=#{@lead.latitude}%2C#{@lead.longitude}" %>
        <br>
        <br>
        <p>
          <b>Last Updated:</b>
          <%= @lead.updated_at.strftime("%B %d, %Y %I:%M%p") %>
        </p>
        <p>
          <b>Created:</b>
          <%= @lead.created_at.strftime("%B %d, %Y") %>
        </p>
      </div>
      <div class="span6">
        <div>
             Status:
            <br> <h5><%= best_in_place @lead, :notes %> </h5>
        </div>
        <hr>
        <br>
        <div>
        <%= render "comments/form" %>
        <%= render "comments/comments" %>
      </div>
      </div>
  </div>